### PR TITLE
New version apis

### PR DESCRIPTION
**Pull request by jpalawaga**
For some reason my old PR stopped updating when I pushed new commits onto the branch :?

anyhow this has a few changes:

- Fixes one broken test--the old attachment id appears to be marked as deleted
- adds support for getting version sets for a project
- adds support to get sheets based on a version set

and, as in the other pr, i'm working with the customer api team to get the api break fixed for the broken  test.

---
This change is [Reviewable](https://reviewable.io/reviews/plangrid/plangrid-api-net/13)

### CODE REVIEW

**Comment by kirkplangrid** [comment]
Looks good, but there seems to be a test failure?  

https://ci.appveyor.com/project/kirkplangrid/plangrid-api-net/build/2.0.8-uabagrmf

```
1) Test Error : PlanGrid.Api.Tests.AttachmentTests.UploadPdfAttachment
   Refit.ApiException : Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass2e`1.<<buildCancellableT
```

Any thoughts?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/13#-:-Kr8gJ0qk9C5aqlVsyP_:b-ggtefg)*

**Comment by jpalawaga** [comment]
Yeah... unforutnately when attachments were migrated from mongo to postgres, it seems as though CAPI had some bug in it. These integration tests are actually what caused that bug to surface.

I've asked the documents team to fix the breakage, but the tests will unforunately be broken until they do :sadpanda:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/13#-:-Kr8r0ammMA7aTzGhos4:b-q1kk9k)*

**Comment by jpalawaga** [comment]
@kirkplangrid good to merge now?

**Comment by kirkplangrid** [comment]
Hey, sorry, lost track of this.  Reviewing now, but will get back to you later this morning.

**Pull request merged**
