### PR TITLE
API Updates as of 7/27/2015

### PR DESCRIPTION
**Pull request by kirkplangrid**
This change is [Reviewable](https://reviewable.io/reviews/plangrid/plangrid-api-net/3)

### CODE REVIEW

**Comment by marchello2000** [comment]
build failed?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-:-KNmRMdKcF9jgv651QHh:874382091)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/Date.cs, line 9 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmRgGpmmA-zWftZpgi:-KNmRgGpmmA-zWftZpgj:-765892212) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/Date.cs#L9)):*
> ```Smalltalk
> namespace PlanGrid.Api
> {
>     public struct Date
> ```

any particular reason it's a struct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by kirkplangrid** [comment]
@marchello2000 The build failed because I removed the test API url from the config file (per Rob's request).  Need to make it an environment variable on the build server.  Since it's using Jenkins, I suppose I can do that msyelf.  

The reason it's a struct is it's an immutable value type like `DateTime`.  Seemed to make sense to me to follow its lead.

**Comment by marchello2000** [comment]
:+1:
(p.s. enabled reviewable on this repo)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-:-KNmUFyQY7RQF2ZHzY_o:2012339377)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/IPlanGridApi.cs, line 154 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmUWwvTePjyM-55UqP:-KNmUWwvTePjyM-55UqQ:1761197594) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/IPlanGridApi.cs#L154)):*
> ```Smalltalk
>         Task<ShareableObject> CreateSheetPacket(string projectUid);
> 
>         [Post("/projects/{projectUid}/sheets/packets/{packetUid}")]
> ```

should it be a `POST` when the method names says `Get`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by kirkplangrid** [comment]
:+1: 

---

Review status: 0 of 42 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[PlanGrid.Api/IPlanGridApi.cs, line 154 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmUWwvTePjyM-55UqP:-KNmUn_hPcK0PYzOmYHi:1851820071) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/IPlanGridApi.cs#L154)):*
<details><summary><i>Previously, marchello2000 (Mark Vulfson) wrote…</i></summary>
> should it be a `POST` when the method names says `Get`?
</details>
Ah, nice catch.  Missed the test for these two methods.  Will add.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-:-KNmUY5nPtij0voKr5pD:-510466975)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/PlanGridApiExtensions.cs, line 109 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmVaKGebtZWmvNEj1q:-KNmVaKHSEyJ4LUXy1EE:1181787685) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/PlanGridApiExtensions.cs#L109)):*
> ```Smalltalk
>         }
> 
>         public static async Task UploadVersion(this IPlanGridApi api, string projectUid, string versionName, params VirtualFile[] files)
> ```

nit: is `UploadVersion` the right name... I thought we are moving towards `UploadGroup` or something like that? If that's what the API says then keep it obviously.. just  curious

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/PlanGridHttpHandler.cs, line 40 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmW69nTpsLUq595InF:-KNmW69ofmHpNFXCs62Z:-1932972420) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/PlanGridHttpHandler.cs#L40)):*
> ```Smalltalk
>             request.Headers.Accept.Add(MediaTypeWithQualityHeaderValue.Parse("application/vnd.plangrid+json; version=1"));
> 
>             HttpResponseMessage response = await base.SendAsync(request, cancellationToken);
> ```

does `SendAsync` not throw?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/PlanGridHttpHandler.cs, line 40 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmW69nTpsLUq595InF:-KNmWA4jrlFhenaZRrdD:1504951067) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/PlanGridHttpHandler.cs#L40)):*
<details><summary><i>Previously, marchello2000 (Mark Vulfson) wrote…</i></summary>
> does `SendAsync` not throw?
</details>
As in, do we need this in a `try`/`catch`? or have the clients handle that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/Rfi.cs, line 37 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmWMlWPBAmuUYo1wpf:-KNmWMlWPBAmuUYo1wpg:-1740825144) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/Rfi.cs#L37)):*
> ```Smalltalk
> 
>         [JsonProperty("sent_date")]
>         public Date? SentDate { get; set; }
> ```

Hm... did they actually change this to a `Date` object? I thought all of backend moved to always have DateTime

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/RfiUpsert.cs, line 28 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmWYiZRd4NLBv1mKeg:-KNmWYiZRd4NLBv1mKeh:1344512800) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/RfiUpsert.cs#L28)):*
> ```Smalltalk
> 
>         [JsonProperty("sent_date")]
>         public Date? SentDate { get; set; }
> ```

same here, re: Date

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by kirkplangrid** [comment]
Review status: 0 of 42 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[PlanGrid.Api/PlanGridApiExtensions.cs, line 109 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmVaKGebtZWmvNEj1q:-KNmWQ-wIH0qm-5zqqB1:1078928335) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/PlanGridApiExtensions.cs#L109)):*
<details><summary><i>Previously, marchello2000 (Mark Vulfson) wrote…</i></summary>
> nit: is `UploadVersion` the right name... I thought we are moving towards `UploadGroup` or something like that? If that's what the API says then keep it obviously.. just  curious
</details>
The endpoint (https://developer.plangrid.com/docs/upload-version-to-project) names it "Upload Version to Project" :)

---

*[PlanGrid.Api/Rfi.cs, line 37 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmWMlWPBAmuUYo1wpf:-KNmWkja_od_SavPHNtJ:-1822937372) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/Rfi.cs#L37)):*
<details><summary><i>Previously, marchello2000 (Mark Vulfson) wrote…</i></summary>
> Hm... did they actually change this to a `Date` object? I thought all of backend moved to always have DateTime
</details>
See: https://developer.plangrid.com/docs/timestamps
For some fields (issue due date, for example) they require the date version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/JsonConverters/DateUrlParameterFormatter.cs, line 13 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmXGl_gTWgKYZC9TWi:-KNmXGl_gTWgKYZC9TWj:-2041208445) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/JsonConverters/DateUrlParameterFormatter.cs#L13)):*
> ```Smalltalk
>             if (value is DateTime)
>             {
>                 return ((DateTime)value).ToString("yyyy-MM-ddTHH\\:mm\\:ss");
> ```

This is ISO8601? do we need `Z` at the end to indicate UTC?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/JsonConverters/DateConverter.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmXR-2BMVEI4JzgPjH:-KNmXR-2BMVEI4JzgPjI:892678775) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/JsonConverters/DateConverter.cs#L11)):*
> ```Smalltalk
>         {
>             var date = (Date)value;
>             writer.WriteValue(date.ToString());
> ```

not sure this will be right in all locales?

Maybe `.ToString("yyyy-MM-ddTHH:mm:ssZ", DateTimeFormatInfo.InvariantInfo)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/JsonConverters/DateConverter.cs, line 17 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmXw7foXUuoWuTUpgT:-KNmXw7foXUuoWuTUpgU:791436976) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/JsonConverters/DateConverter.cs#L17)):*
> ```Smalltalk
>         {
>             string s = (string)reader.Value;
>             return Date.Parse(s);
> ```

as above, assume this is for ISO8601 dates? Then we should:
```
DateTime.ParseExact(s, "u", System.Globalization.CultureInfo.InvariantCulture);
```
Actually, prob should use `u` above as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by kirkplangrid** [comment]
Review status: 0 of 42 files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[PlanGrid.Api/JsonConverters/DateConverter.cs, line 17 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmXw7foXUuoWuTUpgT:-KNmZTsec9-wpe7-Oqh8:563151113) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/JsonConverters/DateConverter.cs#L17)):*
<details><summary><i>Previously, marchello2000 (Mark Vulfson) wrote…</i></summary>
> as above, assume this is for ISO8601 dates? Then we should:
> ```
> DateTime.ParseExact(s, "u", System.Globalization.CultureInfo.InvariantCulture);
> ```
> Actually, prob should use `u` above as well
</details>
What is `"u"`?  I don't see it [here](https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx).  Did you mean `"o"`?  If so, we can't use that because the API currently has a bug which doesn't allow the "Z".  (at least, that was the case yesterday when I reported it to the channel, though Ky was working on it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by kirkplangrid** [comment]
Review status: 0 of 42 files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[PlanGrid.Api/PlanGridHttpHandler.cs, line 40 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmW69nTpsLUq595InF:-KNmZtD2r0558w7uU3hE:1416948231) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/PlanGridHttpHandler.cs#L40)):*
<details><summary><i>Previously, marchello2000 (Mark Vulfson) wrote…</i></summary>
> As in, do we need this in a `try`/`catch`? or have the clients handle that?
</details>
Not sure I entirely follow.  Why would we do a try/catch?  What can we do in the catch?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Comment by marchello2000** [comment]
*[PlanGrid.Api/PlanGridHttpHandler.cs, line 40 \[r1\]](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3#-KNmW69nTpsLUq595InF:-KNma5dkKUVI16bR2zz9:-117509893) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/0dabdf043fe0ae9f9a1e67f6a9db52fa00910a6e/PlanGrid.Api/PlanGridHttpHandler.cs#L40)):*
<details><summary><i>Previously, kirkplangrid (Kirk) wrote…</i></summary>
> Not sure I entirely follow.  Why would we do a try/catch?  What can we do in the catch?
</details>
Don't some network issues manifest as exceptions here? We wrap `SendAsync` in try/catch in our app

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/3)*

**Pull request merged**
