### PR TITLE
Replace RFI sent_date and due_date with sent_at and due_at.

### PR DESCRIPTION
**Pull request by JuliusAlexanderIV**
This change is [Reviewable](https://reviewable.io/reviews/plangrid/plangrid-api-net/7)

### CODE REVIEW

**Comment by kirkplangrid** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[PlanGrid.Api.Tests/PlanGrid.Api.Tests.csproj, line 85 at r1](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/7#-Kct97IZJLfM3whJ0_bs:-Kct97IZJLfM3whJ0_bt:b-les8kn) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/ce5e6b149a67f6c4791f3da469a525fd21cd3688/PlanGrid.Api.Tests/PlanGrid.Api.Tests.csproj#L85)):*
> ```XML
>   <ItemGroup>
>     <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
>   </ItemGroup>
> ```

Do you know what this lineitem is about?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/7)*

**Comment by kirkplangrid** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/7)*

**Comment by JuliusAlexanderIV** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[PlanGrid.Api.Tests/PlanGrid.Api.Tests.csproj, line 85 at r1](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/7#-Kct97IZJLfM3whJ0_bs:-KctHYfrqBwa2CUE_2Fc:b-z1mi3v) ([raw file](https://github.com/plangrid/plangrid-api-net/blob/ce5e6b149a67f6c4791f3da469a525fd21cd3688/PlanGrid.Api.Tests/PlanGrid.Api.Tests.csproj#L85)):*
<details><summary><i>Previously, kirkplangrid (Kirk) wrote…</i></summary><blockquote>

Do you know what this lineitem is about?
</blockquote></details>

I think maybe that happened when I ran the wrong unit testing stuff.  Removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/7)*

**Comment by kirkplangrid** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/plangrid/plangrid-api-net/7#-:-KctIi3EMGyGx-JcynOd:bnfp4nl)*

**Pull request merged**
